### ISSUE TITLE
error

### ISSUE THREAD

**Issue by autpierro** [Navoei/CustomDiscs#11]
Could not load 'plugins/audioplayer-1.19.2-1.4.3.jar' in folder 'plugins'
org.bukkit.plugin.InvalidDescriptionException: Invalid plugin.yml
        at org.bukkit.plugin.java.JavaPluginLoader.getPluginDescription(JavaPluginLoader.java:178) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.loadPlugins(SimplePluginManager.java:155) ~[pufferfish-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.loadPlugins(CraftServer.java:423) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:280) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1128) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
        at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:307) ~[pufferfish-1.19.2.jar:git-Pufferfish-34]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.io.FileNotFoundException: Jar does not contain plugin.yml

**Comment by Navoei** [comment]
This error is from the AudioPlayer mod (developed by Henkelmax). It is a Fabric mod. If you are looking for a Paper fork of his mod head over to the releases page of this repository.
