### ISSUE TITLE
issue when starting server

### ISSUE THREAD

**Issue by artiaaaa** [Navoei/CustomDiscs#17]
Hi
I have some trouble with this plugin
here is what is written in the console:

[14:42:03] [Server thread/INFO]: [CustomDiscs] Enabling CustomDiscs v2.2.3
[14:42:03] [Server thread/INFO]: Successfully registered CustomDiscs plugin
[14:42:03] [Server thread/ERROR]: Error occurred while enabling CustomDiscs v2.2.3 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/format/TextColor
        at me.Navoei.customdiscsplugin.CustomDiscs.onEnable(CustomDiscs.java:58) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:525) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:439) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:584) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:403) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:968) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3606-Spigot-6198b5a-300e744]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.format.TextColor
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?]
        ... 12 more

**Comment by artiaaaa** [comment]
server spigot 1.19.2
protocollib v4.8.0
Simple Voice chat plugin v1.19.2-2.3.13

**Comment by Navoei** [comment]
Hello! The reason this error is occurring is because you are not using Paper. 

This plugin only works when using Paper server software.

**Comment by artiaaaa** [comment]
thank you!
