### ISSUE TITLE
Error when using a hopper on a Jukebox

### ISSUE THREAD

**Issue by derMiepz** [Navoei/CustomDiscs#33]
Freshly updated the plugin (v2.3)
Paper-196 MC 1.19.2

Error:

[19:11:11 ERROR]: Could not pass event InventoryMoveItemEvent to CustomDiscs v2.3
java.lang.NoSuchFieldError: JUKEBOX
        at me.Navoei.customdiscsplugin.HopperManager.onJukeboxEjectToHopper(HopperManager.java:53) ~[custom-discs-2.3.jar:?]
        at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor85.execute(Unknown Source) ~[?:?]
        at org.bukkit.plugin.EventExecutor$2.execute(EventExecutor.java:77) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:git-Paper-380]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:672) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.event.Event.callEvent(Event.java:45) ~[paper-api-1.19.3-R0.1-SNAPSHOT.jar:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.callPushMoveEvent(HopperBlockEntity.java:284) ~[?:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.hopperPush(HopperBlockEntity.java:213) ~[?:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.ejectItems(HopperBlockEntity.java:355) ~[?:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.tryMoveItems(HopperBlockEntity.java:158) ~[?:?]
        at net.minecraft.world.level.block.entity.HopperBlockEntity.pushItemsTick(HopperBlockEntity.java:139) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk$BoundTickingBlockEntity.tick(LevelChunk.java:1304) ~[?:?]
        at net.minecraft.world.level.chunk.LevelChunk$RebindableTickingBlockEntityWrapper.tick(LevelChunk.java:1256) ~[?:?]
        at net.minecraft.world.level.Level.tickBlockEntities(Level.java:899) ~[?:?]
        at net.minecraft.server.level.ServerLevel.tick(ServerLevel.java:740) ~[?:?]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1535) ~[paper-1.19.3.jar:git-Paper-380]
        at net.minecraft.server.dedicated.DedicatedServer.tickChildren(DedicatedServer.java:440) ~[paper-1.19.3.jar:git-Paper-380]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1397) ~[paper-1.19.3.jar:git-Paper-380]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1173) ~[paper-1.19.3.jar:git-Paper-380]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:316) ~[paper-1.19.3.jar:git-Paper-380]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]

**Comment by Navoei** [comment]
The latest version only runs in 1.19.4

**Comment by derMiepz** [comment]
Dang alright. Time to update I guess...
