### ISSUE TITLE
An error has occured while trying to play this disc

### ISSUE THREAD

**Issue by FaceCutter** [Navoei/CustomDiscs#46]
Can't play any music disk on server.
Here's the log from server:

[07:24:26] [AudioPlayerThread/WARN]: javax.sound.sampled.UnsupportedAudioFileException: not a MPEG stream:Cannot invoke "javazoom.jl.decoder.Header.version()" because "m_header" is null
[07:24:26] [AudioPlayerThread/WARN]: 	at custom-discs-2.4.1.jar//javazoom.spi.mpeg.sampled.file.MpegAudioFileReader.getAudioFileFormat(MpegAudioFileReader.java:449)
[07:24:26] [AudioPlayerThread/WARN]: 	at custom-discs-2.4.1.jar//org.tritonus.share.sampled.file.TAudioFileReader.getAudioInputStream(TAudioFileReader.java:387)
[07:24:26] [AudioPlayerThread/WARN]: 	at custom-discs-2.4.1.jar//org.tritonus.share.sampled.file.TAudioFileReader.getAudioInputStream(TAudioFileReader.java:329)
[07:24:26] [AudioPlayerThread/WARN]: 	at custom-discs-2.4.1.jar//javazoom.spi.mpeg.sampled.file.MpegAudioFileReader.getAudioInputStream(MpegAudioFileReader.java:583)
[07:24:26] [AudioPlayerThread/WARN]: 	at custom-discs-2.4.1.jar//javazoom.spi.mpeg.sampled.file.MpegAudioFileReader.getAudioInputStream(MpegAudioFileReader.java:493)
[07:24:26] [AudioPlayerThread/WARN]: 	at custom-discs-2.4.1.jar//me.Navoei.customdiscsplugin.PlayerManager.convertFormat(PlayerManager.java:132)
[07:24:26] [AudioPlayerThread/WARN]: 	at custom-discs-2.4.1.jar//me.Navoei.customdiscsplugin.PlayerManager.readSoundFile(PlayerManager.java:121)
[07:24:26] [AudioPlayerThread/WARN]: 	at custom-discs-2.4.1.jar//me.Navoei.customdiscsplugin.PlayerManager.playChannel(PlayerManager.java:105)
[07:24:26] [AudioPlayerThread/WARN]: 	at custom-discs-2.4.1.jar//me.Navoei.customdiscsplugin.PlayerManager.lambda$playLocationalAudio$4(PlayerManager.java:73)
[07:24:26] [AudioPlayerThread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
[07:24:26] [AudioPlayerThread/WARN]: 	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
[07:24:26] [AudioPlayerThread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:1623)
[07:24:26] [AudioPlayerThread/INFO]: Error Occurred At: Location{world=CraftWorld{name=world},x=215.0,y=73.0,z=-96.0,pitch=0.0,yaw=0.0}

**Comment by Navoei** [comment]
It may be because of the file extension.

**Comment by FaceCutter** [comment]
Tried other format's, still not working(

**Comment by KKolyanGGWP** [comment]
i have that too, but on 1.19.4. Maybe google drive direct link doesnt works?

**Comment by KKolyanGGWP** [comment]
> Tried other format's, still not working(

I FOUND OUT THE PROBLEM
Google drive diret link doesnt works. I searched for sites where you couldve upload music with direct link and found it( Its not an advertisement). https://jukehost.co.uk/ works fine
