### ISSUE TITLE
[ISSUE] I got this issue, I was wondering if it could be solved? 👉👈🥺 

### ISSUE THREAD

**Issue by chrisizatt** [Navoei/CustomDiscs#7]
```
[18:06:25] [Server thread/ERROR]: Error occurred while enabling CustomDiscs v2.0.1 (Is it up to date?)
java.lang.NoClassDefFoundError: net/kyori/adventure/text/format/TextColor
        at me.Navoei.customdiscsplugin.CustomDiscs.onEnable(CustomDiscs.java:42) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:264) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:342) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:480) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugin(CraftServer.java:525) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3574-Spigot-450dcaa-cdef8fc]
        at org.bukkit.craftbukkit.v1_19_R1.CraftServer.enablePlugins(CraftServer.java:439) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3574-Spigot-450dcaa-cdef8fc]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:584) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3574-Spigot-450dcaa-cdef8fc]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:403) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3574-Spigot-450dcaa-cdef8fc]
        at net.minecraft.server.dedicated.DedicatedServer.e(DedicatedServer.java:255) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3574-Spigot-450dcaa-cdef8fc]
        at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:968) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3574-Spigot-450dcaa-cdef8fc]
        at net.minecraft.server.MinecraftServer.lambda$0(MinecraftServer.java:293) ~[spigot-1.19.2-R0.1-SNAPSHOT.jar:3574-Spigot-450dcaa-cdef8fc]
        at java.lang.Thread.run(Thread.java:833) [?:?]
Caused by: java.lang.ClassNotFoundException: net.kyori.adventure.text.format.TextColor
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:147) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:99) ~[spigot-api-1.19.2-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
        ... 12 more
```

**Comment by Navoei** [comment]
Oh my thats my fault :( I forgot that I began using some API that is only available on Paper, if you are using Bukkit or Spigot this plugin will most likely not work.

**Comment by Navoei** [comment]
If you want to use my plugin, please consider switching to Paper.
