### ISSUE TITLE
Error in playback 

### ISSUE THREAD

**Issue by Ricano707** [Navoei/CustomDiscs#73]
Paper 1.20.1
voicechat-bukkit-2.5.16
CustomDiscs-1.4.3

It worked for a while, but now its not working anymore

[11:50:40 ERROR]: Error in playback of n52JKV5SqdM
io.github.subkek.customdiscs.libs.com.sedmelluq.discord.lavaplayer.tools.FriendlyException: Something broke when playing the track.
	at io.github.subkek.customdiscs.libs.com.sedmelluq.discord.lavaplayer.tools.ExceptionTools.wrapUnfriendlyExceptions(ExceptionTools.java:45) ~[CustomDiscs-1.4.3.jar:?]
	at io.github.subkek.customdiscs.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:121) ~[CustomDiscs-1.4.3.jar:?]
	at io.github.subkek.customdiscs.libs.com.sedmelluq.discord.lavaplayer.player.DefaultAudioPlayerManager.lambda$executeTrack$2(DefaultAudioPlayerManager.java:339) ~[CustomDiscs-1.4.3.jar:?]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[?:?]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[?:?]
	at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.RuntimeException: Not success status code: 403
	at io.github.subkek.customdiscs.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.validateStatusCode(PersistentHttpStream.java:88) ~[CustomDiscs-1.4.3.jar:?]
	at io.github.subkek.customdiscs.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.attemptConnect(PersistentHttpStream.java:124) ~[CustomDiscs-1.4.3.jar:?]
	at io.github.subkek.customdiscs.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.connect(PersistentHttpStream.java:106) ~[CustomDiscs-1.4.3.jar:?]
	at io.github.subkek.customdiscs.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.internalRead(PersistentHttpStream.java:158) ~[CustomDiscs-1.4.3.jar:?]
	at io.github.subkek.customdiscs.libs.com.sedmelluq.discord.lavaplayer.tools.io.PersistentHttpStream.read(PersistentHttpStream.java:174) ~[CustomDiscs-1.4.3.jar:?]
	at java.io.DataInputStream.readByte(DataInputStream.java:271) ~[?:?]
	at io.github.subkek.customdiscs.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaEbmlReader.readEbmlInteger(MatroskaEbmlReader.java:39) ~[CustomDiscs-1.4.3.jar:?]
	at io.github.subkek.customdiscs.libs.com.sedmelluq.discord.lavaplayer.container.matroska.format.MatroskaFileReader.readNextElement(MatroskaFileReader.java:47) ~[CustomDiscs-1.4.3.jar:?]
	at io.github.subkek.customdiscs.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaStreamingFile.readFile(MatroskaStreamingFile.java:94) ~[CustomDiscs-1.4.3.jar:?]
	at io.github.subkek.customdiscs.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.loadMatroskaFile(MatroskaAudioTrack.java:52) ~[CustomDiscs-1.4.3.jar:?]
	at io.github.subkek.customdiscs.libs.com.sedmelluq.discord.lavaplayer.container.matroska.MatroskaAudioTrack.process(MatroskaAudioTrack.java:35) ~[CustomDiscs-1.4.3.jar:?]
	at io.github.subkek.customdiscs.libs.com.sedmelluq.discord.lavaplayer.track.DelegatedAudioTrack.processDelegate(DelegatedAudioTrack.java:25) ~[CustomDiscs-1.4.3.jar:?]
	at io.github.subkek.customdiscs.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processStatic(YoutubeAudioTrack.java:148) ~[CustomDiscs-1.4.3.jar:?]
	at io.github.subkek.customdiscs.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.processWithClient(YoutubeAudioTrack.java:116) ~[CustomDiscs-1.4.3.jar:?]
	at io.github.subkek.customdiscs.libs.dev.lavalink.youtube.track.YoutubeAudioTrack.process(YoutubeAudioTrack.java:71) ~[CustomDiscs-1.4.3.jar:?]
	at io.github.subkek.customdiscs.libs.com.sedmelluq.discord.lavaplayer.track.playback.LocalAudioTrackExecutor.execute(LocalAudioTrackExecutor.java:109) ~[CustomDiscs-1.4.3.jar:?]
	... 4 more

**Comment by Athar42** [comment]
CustomDiscs-1.4.3 ??? really ?

I don't even find this version in the releases section (there is a gap between 1.3.1 and 2.0).

Anaways, if you are in 1.20.1 on your server, update the plugin to, at least, release 2.4.1 : https://github.com/Navoei/CustomDiscs/releases/tag/v2.4.1 (2.4 is the release that bring the 1.20.1 support, and the 2.4.1 a couple of fixes)
