### ISSUE TITLE
Error at boot but the plugin still seems to work

### ISSUE THREAD

**Issue by The12thUnique** [Navoei/CustomDiscs#8]
I get this error at when the server is booting -

`[15:01:48] [Server thread/WARN]: java.lang.NullPointerException: Cannot invoke "de.maxhenkel.voicechat.voice.server.ServerVoiceEvents.getServer()" because "de.maxhenkel.voicechat.Voicechat.SERVER" is null
[15:01:48] [Server thread/WARN]: 	at voicechat-bukkit-1.19.2-2.3.1.jar//de.maxhenkel.voicechat.plugins.impl.VoicechatServerApiImpl.registerVolumeCategory(VoicechatServerApiImpl.java:171)
[15:01:48] [Server thread/WARN]: 	at custom-discs-2.1.1.jar//me.Navoei.customdiscsplugin.VoicePlugin.onServerStarted(VoicePlugin.java:63)
[15:01:48] [Server thread/WARN]: 	at voicechat-bukkit-1.19.2-2.3.1.jar//de.maxhenkel.voicechat.plugins.PluginManager.dispatchEvent(PluginManager.java:70)
[15:01:48] [Server thread/WARN]: 	at voicechat-bukkit-1.19.2-2.3.1.jar//de.maxhenkel.voicechat.plugins.PluginManager.onServerStarted(PluginManager.java:101)
[15:01:48] [Server thread/WARN]: 	at voicechat-bukkit-1.19.2-2.3.1.jar//de.maxhenkel.voicechat.voice.server.ServerVoiceEvents.<init>(ServerVoiceEvents.java:36)
[15:01:48] [Server thread/WARN]: 	at voicechat-bukkit-1.19.2-2.3.1.jar//de.maxhenkel.voicechat.Voicechat.lambda$onEnable$0(Voicechat.java:127)
[15:01:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftTask.run(CraftTask.java:101)
[15:01:48] [Server thread/WARN]: 	at org.bukkit.craftbukkit.v1_19_R1.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:483)
[15:01:48] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.v(MinecraftServer.java:1156)
[15:01:48] [Server thread/WARN]: 	at net.minecraft.server.MinecraftServer.lambda$spin$1(MinecraftServer.java:310)
[15:01:48] [Server thread/WARN]: 	at java.base/java.lang.Thread.run(Thread.java:833)
[15:01:48] [Server thread/INFO]: Done (34.491s)! For help, type "help"`

**Comment by Navoei** [comment]
Thats a bug from the Simple Voice Chat developer. Im pretty sure there is a new update that fixes it.

**Comment by The12thUnique** [comment]
Yup that was the problem, I didn't realize that the plugin was being hosted on CurseForge and not Spigotmc.org, because on Spigotmc.org it says last updated "Aug 7" so I didn't click on the download button since first installing the plugin. 

Thanks and I don't know if that is a side effect but the audio quality of my custom disc has increased now that I updated.
